### ISSUE TITLE
Timeout error?

### ISSUE THREAD

**Issue by calvinkflee** [learn-co-curriculum/javascript-arrow-functions#7]
Hi, I'm doing the hoisting lab, and have been getting the following error... I don't think it's related to the actual test?

**Comment by calvinkflee** [comment]
1) hoisting "before all" hook:                                                                                                                                                  
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.                                                                                  
      at Object.done (node_modules/mocha-jsdom/index.js:70:7)                                                                                                                     
      at process.nextTick (node_modules/jsdom/lib/jsdom.js:297:18)                                                                                                                
      at _combinedTickCallback (internal/process/next_tick.js:67:7)                                                                                                               
      at process._tickCallback (internal/process/next_tick.js:98:9)
